/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc switch.lus -n switch */
/* on c77 the 19/02/2026 at 22:06:24 */

#ifndef _SOC2C_PREDEF_TYPES
#define _SOC2C_PREDEF_TYPES
typedef int _boolean;
typedef int _integer;
typedef char* _string;
typedef double _real;
typedef double _double;
typedef float _float;
#define _false 0
#define _true 1
#endif
// end of _SOC2C_PREDEF_TYPES
// User typedef 
#ifndef _switch_switch_TYPES
#define _switch_switch_TYPES
#endif // enf of  _switch_switch_TYPES
// Memoryless soc ctx typedef 
// Memoryfull soc ctx typedef 
/* Lustre_pre_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_pre_ctx_type;

/* Lustre_arrow_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_ctx_type;

/* Lustre_pre_2_ctx */
typedef struct {
   /*Memory cell*/
   _integer _memory ;
} Lustre_pre_2_ctx_type;

/* Lustre_arrow_2_ctx */
typedef struct {
   /*Memory cell*/
   _boolean _memory ;
} Lustre_arrow_2_ctx_type;

/* switch_switch_ctx */
typedef struct {
   /*INSTANCES*/
   Lustre_pre_2_ctx_type Lustre_pre_2_ctx_tab[1];
   Lustre_pre_ctx_type Lustre_pre_ctx_tab[1];
   Lustre_arrow_2_ctx_type Lustre_arrow_2_ctx_tab[1];
   Lustre_arrow_ctx_type Lustre_arrow_ctx_tab[1];
} switch_switch_ctx_type;

