/* This file was generated by lv6 version 6.101.27. */
/*  lv6 -cc switch.lus -n switch */
/* on c77 the 19/02/2026 at 22:06:24 */

#include <stdlib.h>
#include <string.h>

#include "lustre_consts.h"

#ifndef _switch_switch_H_FILE
#define _switch_switch_H_FILE
void Lustre_arrow_ctx_reset(Lustre_arrow_ctx_type* ctx);
Lustre_arrow_ctx_type* Lustre_arrow_ctx_new_ctx();
void Lustre_arrow_step(_boolean ,_boolean ,_boolean *,Lustre_arrow_ctx_type*);

void Lustre_arrow_2_ctx_reset(Lustre_arrow_2_ctx_type* ctx);
Lustre_arrow_2_ctx_type* Lustre_arrow_2_ctx_new_ctx();
void Lustre_arrow_2_step(_integer ,_integer ,_integer *,Lustre_arrow_2_ctx_type*);

void Lustre_pre_ctx_reset(Lustre_pre_ctx_type* ctx);
Lustre_pre_ctx_type* Lustre_pre_ctx_new_ctx();
void Lustre_pre_get(_boolean *,Lustre_pre_ctx_type*);

void Lustre_pre_set(_boolean ,Lustre_pre_ctx_type*);

void Lustre_pre_2_ctx_reset(Lustre_pre_2_ctx_type* ctx);
Lustre_pre_2_ctx_type* Lustre_pre_2_ctx_new_ctx();
void Lustre_pre_2_get(_integer *,Lustre_pre_2_ctx_type*);

void Lustre_pre_2_set(_integer ,Lustre_pre_2_ctx_type*);

void switch_switch_ctx_reset(switch_switch_ctx_type* ctx);
switch_switch_ctx_type* switch_switch_ctx_new_ctx();
void switch_switch_step(_boolean ,_boolean *,_integer *,switch_switch_ctx_type*);

/////////////////////////////////////////////////
#endif
